language: python
dist: xenial
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - python -m pytest --cov-report term-missing --cov=./
  - rm *.txt

after_success:
  - codecov # submit coverage
